config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root path
  root 'pages#home'

  # Redirections (renamed articles)
  get '/fr/labels/conseils', to: redirect('/fr/labels/advice', status: 301)
  get '/fr/utilisateurs/flo/themes/intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/themes/artificial-intelligence', status: 301)

  get '/users/flo/articles/gitlab-installation@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/gitlab-installation-automatique-et-manuel@debian-server', status: 301)
  get '/users/flo/articles/sentry@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/sentry-installation-and-configuration@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/owncloud@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/owncloud-installation-et-configuration@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/rails-installation-complete-sur-un-serveur@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/rails-installation-complete-sur-un-serveur@debian-server', status: 301)
  get '/users/flo/articles/matomo-piwik-installation-et-configuration@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/matomo-piwik-installation-et-configuration@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/alias-indispensables-pour-linux@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/alias-indispensables-pour-linux@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/securisation-du-serveur@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/outils-pour-securiser-un-serveur-debian@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/ssh-configuration@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/ssh-configuration@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/ssl-installation-des-certificats-sur-linux@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/ssl-installation-des-certificats-sur-linux@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/initialisation-du-serveur@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/initialisation-du-serveur@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/redis-installation@serveur-debian', to: redirect('/fr/utilisateurs/flo/articles/redis-installation@debian-server', status: 301)
  get '/fr/utilisateurs/flo/articles/resume-de-python@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/resume-de-python@artificial-intelligence', status: 301)
  get '/fr/utilisateurs/flo/articles/machine-learning-choix-des-modeles-et-donnees@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/machine-learning-choix-des-modeles-et-donnees@artificial-intelligence', status: 301)
  get '/fr/utilisateurs/flo/articles/environnement-de-travail-pycharm-et-anaconda@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/environnement-de-travail-pycharm-et-anaconda@artificial-intelligence', status: 301)
  get '/fr/utilisateurs/flo/articles/panda-evolution-de-numpy@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/decouverte-de-numpy@artificial-intelligence', status: 301)
  get '/fr/utilisateurs/flo/articles/scikit-learn-premiere-approche-du-machine-learning@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/scikit-learn-premiere-approche-du-machine-learning@artificial-intelligence', status: 301)
  get '/fr/utilisateurs/flo/articles/matplotlib-et-seaborn-visualisation-des-donnees@intelligence-artificielle', to: redirect('/fr/utilisateurs/flo/articles/matplotlib-et-seaborn-visualisation-des-donnees@artificial-intelligence', status: 301)

  get '/fr/utilisateurs/flo/articles/dokuwiki-customisation@serveur-debian', to: redirect('/', status: 301)

  localized do
    ### Routes managed by javascript router (routes.jsx)
    # Base routes
    get '/', to: 'pages#home', as: :home, defaults: { name: 'home', public: true }

    # Search
    get '/search(/:query)', to: 'pages#home', as: :search, defaults: { name: 'search', public: true }

    # Users
    get '/users/:user_slug/topics', to: 'pages#user_home', as: :user_home, defaults: { name: 'user_home' }

    get '/users', to: 'pages#home', as: :users, defaults: { name: 'users', public: true }
    get '/users/password/new', to: 'pages#home', as: :new_password, defaults: { name: 'new_password', public: true }
    get '/users/password/edit', to: 'pages#home', as: :edit_password, defaults: { name: 'edit_password', public: true }
    get '/users/confirmation', to: 'pages#home', as: :user_confirm, defaults: { name: 'user_confirm', public: true }
    get '/users/:user_slug', to: 'pages#home', as: :show_user, defaults: { name: 'show_user', public: true }
    get '/users/:user_slug/edit', to: 'pages#home', as: :edit_user, defaults: { name: 'edit_user' }

    # Tags
    get '/tags', to: 'tags#index', as: :tags, defaults: { name: 'tags', public: true }
    get '/tags/:tag_slug', to: 'tags#show', as: :show_tag, defaults: { name: 'show_tag', public: true }
    get '/tags/:tag_slug/edit', to: 'tags#edit', as: :edit_tag, defaults: { name: 'edit_tag' }

    get '/users/:user_slug/topics/:topic_slug/tags', to: 'tags#index', as: :topic_tags, defaults: { name: 'topic_tags', public: true }
    get '/tags/:user_slug/sort', to: 'pages#home', as: :sort_tag, defaults: { name: 'sort_tag' }

    # Topics
    get '/users/:user_slug/topics/:topic_slug/show', to: 'topics#show', as: :user_topic, defaults: { name: 'user_topic', public: true }
    get '/users/:user_slug/topics/:topic_slug/edit', to: 'pages#home', as: :edit_topic, defaults: { name: 'edit_topic' }
    get '/users/:user_slug/topics/:topic_slug/edit-inventories', to: 'pages#home', as: :edit_inventories_topic, defaults: { name: 'edit_inventories_topic' }

    # Articles
    get '/users/:user_slug', to: 'articles#index', as: :user_articles, defaults: { name: 'user_articles', public: true }
    get '/users/:user_slug/topics/:topic_slug', to: 'articles#index', as: :topic_articles, defaults: { name: 'topic_articles', public: true }
    get '/tagged/:tag_slug(/:child_tag_slug)', to: 'articles#index', as: :tagged_articles, defaults: { name: 'tagged_articles', public: true }
    get '/users/:user_slug/topics/:topic_slug/tagged/:tag_slug(/:child_tag_slug)', to: 'articles#index', as: :tagged_topic_articles, defaults: { name: 'tagged_topic_articles', public: true }
    get '/users/:user_slug/articles/:article_slug', to: 'articles#show', as: :user_article, defaults: { name: 'user_article', public: true }
    get '/users/:user_slug/articles/:article_slug/edit', to: 'articles#edit', as: :edit_article, defaults: { name: 'edit_article' }

    get '/users/:user_slug/topics/:topic_slug/order/:order', to: 'pages#home', as: :order_topic_articles, defaults: { name: 'order_topic_articles' }
    get '/users/:user_slug/topics/:topic_slug/:tag_slug/order/:order', to: 'pages#home', as: :order_tagged_topic_articles, defaults: { name: 'order_tagged_topic_articles' }
    get '/users/:user_slug/topics/:topic_slug/sort', to: 'pages#home', as: :sort_topic_articles, defaults: { name: 'sort_topic_articles' }
    get '/articles/shared/:article_slug/:public_link', to: 'pages#home', as: :shared_article, defaults: { name: 'shared_article' }
    get '/users/:user_slug/topics/:topic_slug/article-new', to: 'pages#home', as: :new_article, defaults: { name: 'new_article' }
    get '/users/:user_slug/articles/:article_slug/history', to: 'pages#home', as: :history_article, defaults: { name: 'history_article' }

    # Static routes
    get '/about', to: 'pages#about', as: :about, defaults: { name: 'about', public: true }
    get '/terms', to: 'pages#terms', as: :terms, defaults: { name: 'terms', public: true }
    get '/privacy', to: 'pages#privacy', as: :privacy, defaults: { name: 'privacy', public: true }

    # Other unnamed routes
    get '/search/*path', to: 'pages#home', defaults: { public: true }
    get '/tags/*path', to: 'pages#home', defaults: { public: true }
    get '/tagged/*path', to: 'pages#home', defaults: { public: true }
    get '/articles/*path', to: 'pages#home', defaults: { public: true }
    get '/users/*path', to: 'pages#home', defaults: { public: true }

    get '/404', to: 'pages#not_found', as: :not_found, defaults: { public: true }
  end

  get '/meta-tags', to: 'pages#meta_tag', as: :meta_tag
  get '/feed', to: 'pages#feed', as: :feed

  # Concerns
  concern :tracker do |options|
    post    :clicked,   to: "#{options[:module]}#clicked"
    post    :viewed,    to: "#{options[:module]}#viewed"
  end

  concern :comments do |options|
    get     :comments,  to: "#{options[:module]}#comments"
    post    :comments,  to: "#{options[:module]}#add_comment"
    put     :comments,  to: "#{options[:module]}#update_comment"
    delete  :comments,  to: "#{options[:module]}#remove_comment"
  end

  concern :outdated do |options|
    resource :outdated, controller: 'outdated', only: [:create, :destroy], **options
  end

  concern :archived do |options|
    resource :archived, controller: 'archived', only: [:create, :destroy], **options
  end

  concern :votes do |options|
    resource :votes, controller: 'votes', only: [:create, :destroy], **options
  end

  # Redirect user connection to home
  get '/api/v1/users/sign_in', to: redirect('/', status: 301), constraints: { format: 'html' }

  # API
  namespace :api, as: nil do
    namespace :v1, as: nil do
      # Users (devise)
      devise_scope :user do
        get     'signup',   to: 'users/registrations#new',    as: :signup
        post    'signup',   to: 'users/registrations#create'
        get     'login',    to: 'users/sessions#new',         as: :login
        post    'login',    to: 'users/sessions#create'
        delete  'logout',   to: 'users/sessions#destroy',     as: :logout
      end

      devise_for :users, controllers: {

app/views/layouts/_flash_messages.html.slim
#notification-component.notification-container

- if flash.present?
  div style="display: none"
    - flash.each do |message_type, message|
      - if message
        .blog-flash data-level="#{message_type}" data-flash-token="#{Time.current.to_fs(:number)}"
          = message.html_safe

app/views/layouts/_head.html.slim
head itemscope="" itemtype="http://schema.org/WebSite"
  meta charset="utf-8"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  
  / Managed also by react helmet
  = display_meta_tags(reverse: true, separator: '|')

  = csrf_meta_tags
  
  - if Rails.env.production?
    link rel="dns-prefetch" href="#{ENV['ASSETS_HOST']}"
    link rel="dns-prefetch" href="https://#{ENV['METRICS_ADDRESS']}"

  = favicon AssetManifest.image_path('favicon.ico'), rel: 'shortcut icon'
  
  = favicon_link_tag AssetManifest.image_path('logos/favicon-16x16.png'), rel: 'icon', type: 'image/png', sizes: '16x16'
  = favicon_link_tag AssetManifest.image_path('logos/favicon-32x32.png'), rel: 'icon', type: 'image/png', sizes: '32x32'
  = favicon_link_tag AssetManifest.image_path('logos/favicon-96x96.png'), rel: 'icon', type: 'image/png', sizes: '96x96'
  = favicon_link_tag AssetManifest.image_path('logos/favicon-160x160.png'), rel: 'icon', type: 'image/png', sizes: '160x160'
  = favicon_link_tag AssetManifest.image_path('logos/favicon-192x192.png'), rel: 'icon', type: 'image/png', sizes: '192x192'
  
  = favicon_link_tag AssetManifest.image_path('logos/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png'
  = favicon_link_tag AssetManifest.image_path('logos/favicon-192x192.png'), rel: 'apple-touch-startup-image', type: 'image/png'
  
  / Manifest for PWA
  - if current_user
    link rel="manifest" href="/manifest.json"
  / For Android only
  meta name="theme-color" content="#199332"
  / For iOS only
  meta name="mobile-web-app-capable" content="yes"
  meta name="apple-mobile-web-app-status-bar-style" content="#199332"
  meta name="apple-mobile-web-app-title" content="#{ENV['WEBSITE_NAME']}"

  / RSS
  = auto_discovery_link_tag :rss, feed_url(format: :rss, locale: I18n.locale)

  / Open search
  link rel="search" type="application/opensearchdescription+xml" href="#{ENV['WEBSITE_URL']}/opensearch.xml?locale=#{I18n.locale}" title="#{ENV['WEBSITE_NAME']}"

  - if Rails.env.production?
    link rel="preload" href="#{AssetManifest.asset_path('Roboto-Regular.woff2')}" as="font" type="font/woff2" crossorigin="anonymous"
    link rel="preload" href="#{AssetManifest.asset_path('Roboto-Medium.woff2')}" as="font" type="font/woff2" crossorigin="anonymous"
    link rel="preload" href="#{AssetManifest.asset_path('Roboto-Bold.woff2')}" as="font" type="font/woff2" crossorigin="anonymous"
    link rel="preload" href="#{AssetManifest.asset_path('Roboto-Italic.woff2')}" as="font" type="font/woff2" crossorigin="anonymous"
  
    - if %w[user_article].include?(request.path_parameters[:name])
      link rel="preload" href="#{AssetManifest.javascript_path('article-show.js')}" as="script"
    - elsif %w[user_articles topic_articles tagged_topic_articles tagged_articles].include?(request.path_parameters[:name])
      link rel="preload" href="#{AssetManifest.javascript_path('article-index.js')}" as="script"
      link rel="preload" href="#{AssetManifest.stylesheet_path('article-index.css')}" as="style"
    - elsif user_signed_in?
      link rel="preload" href="#{AssetManifest.javascript_path('user.js')}" as="script"
      link rel="preload" href="#{AssetManifest.stylesheet_path('pages/user.css')}" as="style"
    - elsif request.path_parameters[:name].blank?
      link rel="preload" href="#{AssetManifest.javascript_path('default.js')}" as="script"
      link rel="preload" href="#{AssetManifest.stylesheet_path('pages/default.css')}" as="style"

app/views/layouts/_javascript.html.slim
#dropdown-component

script#translations type="application/json"
  = yield(:translations)
  
script#application-routes type="application/json"
  = raw localized_routes.to_json
  
script#settings type="application/json"
  = raw InRailsWeBlog.settings.to_h.to_json

javascript:
    window.I18n = {};
    window.defaultLocale = "#{I18n.default_locale}";
    window.locale = "#{I18n.locale}";
    window.locales = #{I18n.available_locales.to_json.html_safe};
    window.defaultMetaTags = #{meta_tags&.meta_tags.to_json.html_safe};

    window.websiteUrl = "#{ENV['WEBSITE_URL']}";
    window.logoUrl = "#{image_url('logos/favicon-192x192.png')}";
    window.termsUrl = "#{terms_path}";

    window.revision = "#{REVISION}";

    window.seoMode = #{@seo_mode};

- if Rails.env.production?
  javascript:
      window.SENTRY_JAVASCRIPT_KEY = "#{ENV['SENTRY_JAVASCRIPT_KEY']}";

      window.METRICS_ADDRESS = "#{ENV['METRICS_ADDRESS']}";
      window.METRICS_SITE_NUMBER = "#{ENV['METRICS_SITE_NUMBER']}";
      window.METRICS_FILENAME = "#{ENV['METRICS_FILENAME']}";

      window._paq = window._paq || [];
    
- if Rails.env.production? && !current_admin && !@seo_mode
  javascript:
      window.isMetricsEnabled = !!window._paq && !window.seoMode;

- if current_user
  javascript:
      window.currentUserId = "#{current_user.id}";
      window.currentUserSlug = "#{current_user.slug}";
      window.currentTopicId = "#{current_user.current_topic_id}";
      window.currentTopicSlug = "#{current_user.current_topic&.slug}";

- if current_admin
  javascript:
      window.currentAdminId = "#{current_admin.id}";
      window.currentAdminPseudo = "#{current_admin.pseudo}";

- if @tracking_params.present?
  javascript:
      window.trackingData = window.trackingData || {};

  - @tracking_params.each do |var, value|
    javascript:
        window.trackingData["#{var}"] = #{raw value.to_json};

= yield(:javascript_initial)
= yield(:javascript)

app/views/layouts/_metrics.html.slim
javascript:
    if (window.isMetricsEnabled) {
        window._paq.push([function () {
            var self = this;

            function getOriginalVisitorCookieTimeout() {
                var now = new Date(),
                    nowTs = Math.round(now.getTime() / 1000),
                    visitorInfo = self.getVisitorInfo();
                var createTs = parseInt(visitorInfo[2]);
                var cookieTimeout = 33696000; // 13 months
                var originalTimeout = createTs + cookieTimeout - nowTs;
                return originalTimeout;
            }

            this.setVisitorCookieTimeout(getOriginalVisitorCookieTimeout());
        }]);
    }

- if current_user
  javascript:
      if (window.isMetricsEnabled) {
          window._paq.push(['setUserId', "#{current_user.pseudo}"]);
      }

javascript:
    if (window.isMetricsEnabled) {
        window._paq.push(['trackPageView']);
        window._paq.push(['enableLinkTracking']);
        window._paq.push(['trackAllContentImpressions']);
    }

noscript
  p
    img alt="" src="//#{ENV['METRICS_ADDRESS']}/#{ENV['METRICS_FILENAME']}.php?idsite=#{ENV['METRICS_SITE_NUMBER']}" style="border:0;"

app/views/layouts/_stylesheet.html.slim
= yield(:stylesheet)

app/views/layouts/admin.html.slim
doctype html
html lang="#{I18n.locale}"

  = render 'layouts/head'
  
  - translations "admin-#{I18n.locale}"

  body
    = yield

    = render 'layouts/flash_messages', flash: flash
    
    - stylesheet 'pages/admin'
    = render 'layouts/stylesheet'
    
    - unless current_page?(admins_login_path)
      - javascript 'admins'
    = render 'layouts/javascript'

app/views/layouts/application.html.slim
doctype html
html lang="#{I18n.locale}"

  = render 'layouts/head'
  
  - translations "default-#{I18n.locale}"

  body class="lang-#{I18n.locale}"
    = yield

    = render 'layouts/flash_messages', flash: flash
    
    - stylesheet 'pages/default'
    = render 'layouts/stylesheet'
    
    - javascript 'default'
    = render 'layouts/javascript'

    - if ENV['METRICS_ADDRESS'].present? && Rails.env.production? && !@seo_mode && !current_admin
      = render 'layouts/metrics'

app/views/layouts/exporter.html.slim
doctype html
html lang="#{I18n.locale}"
head
  meta charset="utf-8"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta http-equiv="Content-Type" content="text/html;charset=utf-8"
  meta name="exporter-version" content="#{ENV['WEBSITE_NAME']} (#{I18n.locale});"

  = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'

  title
    = @title

  css:
      html {
          font-size: 17px;
          line-height: 1.5;
          font-family: "Roboto", "Helvetica", "Arial", sans-serif;
          -moz-osx-font-smoothing: grayscale;
          -webkit-font-smoothing: antialiased;
          font-smoothing: antialiased;
          font-weight: 400;
          color: rgba(0, 0, 0, .87);
          box-sizing: border-box;
      }

      *, *:before, *:after {
          box-sizing: inherit;
      }

      a {
          -webkit-tap-highlight-color: transparent;
          color: #5b96ec;
          text-decoration: none;
          word-wrap: break-word;
      }

      .container {
          position: relative;
          margin: 0 auto;
          max-width: 1280px;
          width: 90%;
      }

      .normalized-content {
          color: rgba(0, 0, 0, .87);
          font-size: 1rem;
          font-weight: 400;
          letter-spacing: .00938em;
          line-height: 1.5;
          overflow-wrap: break-word;
      }

      h1, h2, h3, h4, h5, h6, dl, dd, ol, ul, li, menu, figure, blockquote, p, form, b, i, th, td {
          margin: 0;
          padding: 0;
      }

      h1, h2 {
          margin-top: 2rem;
          margin-bottom: .5rem;
      }

      h1 + h3, h2 + h3, h1 + p, h2 + p {
          margin-top: .8rem;
      }

      h3 {
          margin-top: 1.8rem;
          margin-bottom: .5rem;
      }

      h3 + h4, h3 + p {
          margin-top: .8rem;
      }

      h4 {
          margin-top: 1.4rem;
          margin-bottom: .5rem;
      }

      h4 + h5, h4 + p {
          margin-top: .8rem;
      }

      h5 {
          margin-top: 1.4rem;
          margin-bottom: .5rem;
      }

      h5 + p {
          margin-top: .8rem;
      }

      h1 {
          clear: left;
          font-size: 2.6rem;
          font-style: normal;
          font-weight: 700;
          letter-spacing: .03px;
          line-height: 1.2;
          text-align: left;
      }

      h2 {
          clear: left;
          font-size: 2.2rem;
          font-style: normal;
          font-weight: 500;
          letter-spacing: 1.2px;
          line-height: 1.2;
          text-align: left;
      }

      h3 {
          clear: left;
          font-size: 1.6rem;
          font-style: normal;
          font-weight: 500;
          letter-spacing: 1.2px;
          line-height: 1.2;
          text-align: left;
      }

      h4 {
          clear: left;
          font-size: 1.3rem;
          font-style: normal;
          font-weight: 400;
          line-height: 1.1;
          text-align: left;
      }

      h5, h6 {
          clear: left;
          font-size: 1.15rem;
          font-style: normal;
          font-weight: 400;
          line-height: 1.1;
          text-align: left;
      }

      p {
          margin-top: 1.2rem;
          white-space: pre-wrap;
          font-weight: 400;
          font-style: normal;
          line-height: 1.92;
      }

      b, strong {
          font-weight: 700;
      }

      img {
          max-width: 100%;
      }

      a {
          color: #1cd13b;
      }

      a:visited {
          color: #199332;
      }

      ul {
          margin-top: 1rem;
          padding: 0;
      }

      ul li {
          list-style-type: disc !important;
          margin-bottom: .4rem;
          margin-left: 2rem;
      }

      ol {
          margin-top: .8rem;
          padding: 0;
      }

      ol li {
          list-style-type: decimal !important;
          margin-bottom: .4rem;
          margin-left: 2rem;
      }

      code {
          padding: 2px 4px;
          font-size: 90%;
          font-weight: 400;
          letter-spacing: 0.00938rem;
          color: #001565;
          background-color: #5f64c518;
          border-radius: 4px;
      }
      
      code code {
          font-size: inherit;
          padding: 0;
          color: inherit;
          background: none;
      }

      blockquote {
          border-left: 3px solid rgba(0, 0, 0, .15);
          font-style: italic;
          font-weight: 400;
          margin-left: -2rem;
          padding-bottom: 3px;
          padding-left: 2.5rem;
      }

      pre {
          display: block;
          border: 2px solid #e4e4e4;
          border-radius: .25rem;
          margin: .8rem .4rem;
          white-space: pre-wrap;
          word-wrap: break-word;
      }

      pre code {
          background-color: inherit;
          border: none;
          padding: 0;
          font-size: inherit;
      }

      table {
          margin-top: 1.2rem;
          width: 100%;
          border-collapse: collapse;
      }

      table td, table th {
          padding: 5px 3px;
          border: 1px solid #ececec;
      }

      table sup {
          vertical-align: super;
      }

      table sub {
          vertical-align: sub;
      }

      .secret {
          background-color: #ffd2c4;
          border-left: 6px solid #ff5d2b
      }

      .advice,
      .secret {
          padding: .8rem 1rem;
          margin: .6rem 0 !important;
          border-radius: 3px
      }

      .advice {
          background-color: #b2e5fc;
          border-left: 6px solid #1fb3f6
      }

      .deadend {
          background-color: #d2c5c1;
          padding: .8rem 1rem;
          border-left: 6px solid #90746a;
          margin: .6rem 0 !important;
          border-radius: 3px
      }

      .dead-link {
          color: #f77970 !important;
          text-decoration: line-through
      }

      .tags {
          display: flex;
          flex-wrap: wrap;
          margin-top: 1.5rem;
          align-items: start;
          margin-bottom: 50px;
      }

      .tag {
          margin: 8px;
          color: rgba(0, 0, 0, 0.63);
          cursor: pointer;
          font-size: .9rem;
          font-weight: 600;
          border-radius: 4px;
          padding: 10px;
          border: 1px solid rgba(0, 0, 0, 0.63);
          background-color: transparent;
          height: 32px;
          display: inline-flex;
          outline: 0;
          box-sizing: border-box;
          align-items: center;
          white-space: nowrap;
          vertical-align: middle;
          justify-content: center;
          text-decoration: none;
          word-wrap: break-word;
      }

body
  = yield

app/views/layouts/user.html.slim
doctype html
html lang="#{I18n.locale}"

  = render 'layouts/head'
  
  - translations "user-#{I18n.locale}"

  body class="lang-#{I18n.locale}"
    = yield

    = render 'layouts/flash_messages', flash: flash
    
    - stylesheet 'pages/user', 'user'
    = render 'layouts/stylesheet'
    
    - javascript 'user'
    = render 'layouts/javascript'

    - if ENV['METRICS_ADDRESS'].present? && Rails.env.production? && !@seo_mode && !current_admin
      = render 'layouts/metrics'